rider1 = Rider.create(name: Faker::Name.name)
rider2 = Rider.create(name: Faker::Name.name)
rider3 = Rider.create(name: Faker::Name.name)
rider4 = Rider.create(name: Faker::Name.name)
rider5 = Rider.create(name: Faker::Name.name)
rider6 = Rider.create(name: Faker::Name.name)
rider7 = Rider.create(name: Faker::Name.name)
rider8 = Rider.create(name: Faker::Name.name)
rider9 = Rider.create(name: Faker::Name.name)
rider10 = Rider.create(name: Faker::Name.name)

driver1 = Driver.create(name: Faker::Name.name, car:Faker::Vehicle.vin)
driver2 = Driver.create(name: Faker::Name.name, car:Faker::Vehicle.vin)
driver3 = Driver.create(name: Faker::Name.name, car:Faker::Vehicle.vin)
driver4 = Driver.create(name: Faker::Name.name, car:Faker::Vehicle.vin)
driver5 = Driver.create(name: Faker::Name.name, car:Faker::Vehicle.vin)
driver6 = Driver.create(name: Faker::Name.name, car:Faker::Vehicle.vin)

Receipt.create(driver:driver1, rider: rider1)
Receipt.create(driver:driver2, rider: rider1)
Receipt.create(driver:driver3, rider: rider1)
Receipt.create(driver:driver1, rider: rider7)
Receipt.create(driver:driver2, rider: rider2)
Receipt.create(driver:driver3, rider: rider9)
Receipt.create(driver:driver4, rider: rider9)
Receipt.create(driver:driver4, rider: rider10)
Receipt.create(driver:driver2, rider: rider1)
Receipt.create(driver:driver2, rider: rider3)
Receipt.create(driver:driver1, rider: rider3)
Receipt.create(driver:driver3, rider: rider2)
Receipt.create(driver:driver3, rider: rider4)
Receipt.create(driver:driver5, rider: rider6)
Receipt.create(driver:driver5, rider: rider7)
Receipt.create(driver:driver5, rider: rider8)
Receipt.create(driver:driver1, rider: rider7)
